CREATE TABLE financeiro(
FIN_ID SERIAL NOT NULL PRIMARY KEY,
FIN_NUMERO INTEGER,
FIN_EMISSAO VARCHAR(8),
FIN_VENCIMENTO VARCHAR(8),
FIN_PAGAMENTO VARCHAR(8),
FIN_VALOR float(2),
FIN_JUROS float(2),
FIN_MULTA float(2),
FIN_DESCONTO float(2),
FIN_TOTAL float(2)
)



CREATE TABLE cliente(
CLIE_ID SERIAL NOT NULL PRIMARY KEY,
CLIE_NOME VARCHAR(80),
CLIE_CPF VARCHAR(11),
CLIE_EMAIL VARCHAR(40),
CLIE_DDD INTEGER,
CLIE_TELEFONE INTEGER



)


CREATE TABLE fornecedor(
FORNEC_ID SERIAL NOT NULL PRIMARY KEY,
FORNEC_NOME VARCHAR(80),
FORNEC_RAZSOCIAL VARCHAR(80),
FORNEC_CNPJ VARCHAR(14),
FORNEC_EMAIL VARCHAR(40),
FORNEC_DDD INTEGER,
FORNEC_TELEFONE INTEGER
/* Endereço completo precisa normalizar*/
)

CREATE TABLE ESTADO(
EST_ID SERIAL NOT NULL PRIMARY KEY,
EST_NOME VARCHAR(60)
)

CREATE TABLE ENDERECO_FORNECEDOR(
ENDFORNEC_ID SERIAL NOT NULL,
ENDFORNEC_CIDADE VARCHAR(40),
ENDFORNEC_LOGRADOURO VARCHAR(40),
ENDFORNEC_TIPO VARCHAR (20),
ENDFORNEC_ESTADOFK INT,
ENDFORNEC_FORNECFK int,

CONSTRAINT FK_ESTADO
      FOREIGN KEY(ENDFORNEC_ESTADOFK) 
	  REFERENCES ESTADO(EST_ID),
	  
CONSTRAINT FK_FORNECEDOR
      FOREIGN KEY(ENDFORNEC_FORNECFK) 
	  REFERENCES FORNECEDOR(FORNEC_ID)
)

CREATE TABLE ENDERECO_CLIENTE(
ENDCLIE_ID SERIAL NOT NULL PRIMARY KEY,
ENDCLIE_CIDADE VARCHAR(40),
ENDCLIE_LOGRADOURO VARCHAR(40),
ENDCLIE_TIPO VARCHAR (20),
ENDCLIE_ESTADOFK INT,
ENDCLIE_CLIEFK INT,

CONSTRAINT FK_ESTADO
      FOREIGN KEY(ENDCLIE_ESTADOFK) 
	  REFERENCES ESTADO(EST_ID)
	  

)



INSERT INTO estado (EST_ID, EST_NOME) 
VALUES
(0, 'Acre'),
(1, 'Alagoas'),
(2, 'Amapa'),
(3, 'Amazonas'),
(4, 'Bahia'),
(5, 'Ceara'),
(6, 'Distrito Federal'),
(7, 'Espirito Santo'),
(8, 'Goias'),
(9, 'Maranhao'),
(10,'Mato Grosso'),
(11,'Mato Grosso do Sul'),
(12,'Minas Gerais'),
(13, 'Para'),
(14, 'Paraiba'),
(15, 'Parana'),
(16, 'Pernambuco'),
(17, 'Piaui'),
(18, 'Rio de Janeiro'),
(19, 'Rio Grande do Norte'),
(20, 'Rio Grande do Sul'),
(21, 'Rondonia'),
(22, 'Roraima'),
(23, 'Santa Catarina'),
(24, 'Sao Paulo'),
(25, 'Sergipe'),
(26, 'Tocantins')


CREATE TABLE RECEBER (
REC_ID SERIAL NOT NULL PRIMARY KEY,
REC_NFE VARCHAR(20),
REC_CLIEIDFK INTEGER,
REC_FINIDFK INTEGER,

CONSTRAINT FK_FINANCEIRO
      FOREIGN KEY(REC_FINIDFK) 
	  REFERENCES FINANCEIRO(FIN_ID),

	  CONSTRAINT FK_CLIENTE
      FOREIGN KEY(REC_CLIEIDFK) 
	  REFERENCES CLIENTE(CLIE_ID)

)

CREATE TABLE PAGAR(
PAG_ID SERIAL NOT NULL PRIMARY KEY,
PAG_BOLETO INTEGER,
PAG_FINIDFK INTEGER,
PAG_FORNECIDFK INTEGER,

CONSTRAINT FK_FINANCEIRO
      FOREIGN KEY(PAG_FINIDFK) 
	  REFERENCES FINANCEIRO(FIN_ID),
	  
CONSTRAINT FK_FORNECEDOR
      FOREIGN KEY(PAG_FORNECIDFK) 
	  REFERENCES FORNECEDOR(FORNEC_ID)

)


CREATE TABLE ENDERECO(
END_ID SERIAL NOT NULL PRIMARY KEY,
END_CIDADE VARCHAR(40),
END_LOGRADOURO VARCHAR(40),
END_TIPO VARCHAR (20),
END_ESTADOFK INT,


CONSTRAINT FK_ESTADO
      FOREIGN KEY(END_ESTADOFK) 
	  REFERENCES ESTADO(EST_ID)
)

CREATE TABLE USUARIO(
USU_ID SERIAL NOT NULL PRIMARY KEY,
USU_LOGIN VARCHAR(20),
USU_SENHA VARCHAR(20)
)

INSERT INTO USUARIO (USU_ID, USU_LOGIN, USU_SENHA) 
VALUES (2, 'giovani', '1234')


ALTER TABLE public.cliente ALTER COLUMN clie_nome TYPE varchar(30) USING clie_nome::varchar;
ALTER TABLE public.cliente ALTER COLUMN clie_email TYPE varchar(30) USING clie_email::varchar;
ALTER TABLE public.cliente ALTER COLUMN clie_ddd TYPE int4 USING clie_ddd::int4;
ALTER TABLE public.cliente ALTER COLUMN clie_telefone TYPE int4 USING clie_telefone::int4;


DROP TABLE public.financeiro;

ALTER TABLE public.financeiro ALTER COLUMN fin_emissao TYPE date(0) USING fin_emissao::date;
ALTER TABLE public.financeiro ALTER COLUMN fin_vencimento TYPE date(0) USING fin_vencimento::date;
ALTER TABLE public.financeiro ALTER COLUMN fin_pagamento TYPE date(0) USING fin_pagamento::date;

ALTER TABLE public.cliente DROP COLUMN end_id CASCADE;


